import { useEffect, useState, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { useSound } from "../hooks/useSound";
import { BRAINROT_LEVELS } from "../constants";

// ─── Particle component ───────────────────
function Particle({ style }) {
  return <div className="particle" style={style} />;
}

// ─── Floating emoji ───────────────────────
function FloatingEmoji({ emoji, style }) {
  return (
    <div
      className="absolute text-2xl pointer-events-none select-none opacity-20 animate-float"
      style={style}
    >
      {emoji}
    </div>
  );
}

// ─── Stat card ────────────────────────────
function StatCard({ value, label, icon }) {
  const [displayed, setDisplayed] = useState(0);
  const ref = useRef(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          let start = 0;
          const end = parseInt(value.replace(/\D/g, ""));
          const duration = 1500;
          const increment = end / (duration / 16);
          const timer = setInterval(() => {
            start += increment;
            if (start >= end) {
              setDisplayed(end);
              clearInterval(timer);
            } else {
              setDisplayed(Math.floor(start));
            }
          }, 16);
          observer.disconnect();
        }
      },
      { threshold: 0.5 }
    );
    if (ref.current) observer.observe(ref.current);
    return () => observer.disconnect();
  }, [value]);

  const suffix = value.replace(/[0-9]/g, "").trim();

  return (
    <div ref={ref} className="glass-card p-6 text-center hover:scale-105 transition-transform duration-300">
      <div className="text-3xl mb-2">{icon}</div>
      <div className="text-3xl font-display font-bold gradient-text">
        {displayed.toLocaleString()}{suffix}
      </div>
      <div className="text-white/50 text-sm mt-1">{label}</div>
    </div>
  );
}

// ─── Level card ───────────────────────────
function LevelCard({ level, index }) {
  return (
    <div
      className="glass-card p-4 flex items-center gap-3 hover:scale-105 transition-all duration-300 animate-fade-up"
      style={{
        animationDelay: `${index * 80}ms`,
        borderColor: level.borderColor,
        background: level.bgColor,
      }}
    >
      <div className="text-2xl">{level.emoji}</div>
      <div className="flex-1 min-w-0">
        <div className="font-semibold text-sm text-white/90 truncate">{level.level}</div>
        <div className="text-xs text-white/40">{level.min}–{level.max} pts</div>
      </div>
      <div
        className="w-2 h-2 rounded-full flex-shrink-0"
        style={{ background: level.color, boxShadow: `0 0 6px ${level.color}` }}
      />
    </div>
  );
}

// ─── Feature card ─────────────────────────
function FeatureCard({ icon, title, description, delay }) {
  return (
    <div
      className="glass-card p-6 hover:scale-105 transition-all duration-300 group animate-fade-up"
      style={{ animationDelay: `${delay}ms` }}
    >
      <div className="text-4xl mb-4 group-hover:scale-110 transition-transform duration-300">{icon}</div>
      <h3 className="font-display font-bold text-white mb-2">{title}</h3>
      <p className="text-white/50 text-sm leading-relaxed">{description}</p>
    </div>
  );
}

// ─── MAIN LANDING ─────────────────────────
export default function Landing() {
  const navigate = useNavigate();
  const { sounds } = useSound();
  const [particles, setParticles] = useState([]);

  useEffect(() => {
    const emojis = ["🧠", "⚡", "🔥", "💀", "👑", "🎯", "🚀", "💎"];
    const generated = Array.from({ length: 20 }, (_, i) => ({
      id: i,
      emoji: emojis[Math.floor(Math.random() * emojis.length)],
      style: {
        left: `${Math.random() * 100}%`,
        top: `${Math.random() * 100}%`,
        animationDelay: `${Math.random() * 3}s`,
        animationDuration: `${3 + Math.random() * 4}s`,
        fontSize: `${1 + Math.random() * 1.5}rem`,
      },
    }));
    setParticles(generated);
  }, []);

  const handleStart = () => {
    sounds.click();
    navigate("/quiz");
  };

  const features = [
    {
      icon: "🤖",
      title: "AI-Powered Questions",
      description: "Every quiz is uniquely generated by Groq AI in real-time. No two tests are the same.",
    },
    {
      icon: "🏆",
      title: "Global Leaderboard",
      description: "Compete against players worldwide. Rise through the ranks and claim your spot.",
    },
    {
      icon: "⚡",
      title: "Lightning Fast",
      description: "Powered by Groq's ultra-fast inference. Questions generated in milliseconds.",
    },
    {
      icon: "🎯",
      title: "7 Brainrot Tiers",
      description: "From NPC Energy to Final Boss Sigma — discover exactly how cooked you are.",
    },
    {
      icon: "📱",
      title: "Share Your Results",
      description: "Flex your brainrot level on Twitter, Instagram, WhatsApp and more.",
    },
    {
      icon: "🔥",
      title: "No Signup Needed",
      description: "Just enter your name and start. Free forever, no accounts, no BS.",
    },
  ];

  const stats = [
    { value: "10", label: "Questions Per Test", icon: "❓" },
    { value: "7", label: "Brainrot Levels", icon: "🎯" },
    { value: "100", label: "Max Score Possible", icon: "💯" },
    { value: "20", label: "Seconds Per Question", icon: "⏱️" },
  ];

  return (
    <div className="relative overflow-hidden">
      {/* ── Background ── */}
      <div className="fixed inset-0 -z-10">
        <div className="absolute inset-0 bg-hero-gradient" />
        <div className="absolute inset-0 bg-grid opacity-40" />
        {/* Gradient orbs */}
        <div className="absolute top-20 left-10 w-96 h-96 rounded-full blur-3xl opacity-20"
          style={{ background: "radial-gradient(circle, #7c3aed, transparent)" }} />
        <div className="absolute bottom-20 right-10 w-96 h-96 rounded-full blur-3xl opacity-20"
          style={{ background: "radial-gradient(circle, #ec4899, transparent)" }} />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] rounded-full blur-3xl opacity-10"
          style={{ background: "radial-gradient(circle, #06b6d4, transparent)" }} />
      </div>

      {/* ── Floating Emojis ── */}
      <div className="fixed inset-0 -z-5 pointer-events-none overflow-hidden">
        {particles.map((p) => (
          <FloatingEmoji key={p.id} emoji={p.emoji} style={p.style} />
        ))}
      </div>

      {/* ════════════════════════════════════ */}
      {/*              HERO SECTION           */}
      {/* ════════════════════════════════════ */}
      <section className="min-h-[92vh] flex flex-col items-center justify-center px-4 py-16 text-center">
        {/* Badge */}
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full mb-8 animate-fade-in"
          style={{
            background: "rgba(124,58,237,0.15)",
            border: "1px solid rgba(124,58,237,0.3)",
          }}>
          <span className="w-2 h-2 bg-green-400 rounded-full animate-pulse" />
          <span className="text-sm font-medium text-purple-300">
            AI-Powered · Free · No Signup
          </span>
        </div>

        {/* Main Heading */}
        <div className="animate-fade-up">
          <h1 className="text-5xl sm:text-6xl md:text-7xl lg:text-8xl font-display font-bold leading-none mb-6">
            <span className="block text-white">How</span>
            <span className="block gradient-text">Cooked</span>
            <span className="block text-white">Is Your Brain?</span>
          </h1>
        </div>

        {/* Subheading */}
        <p className="text-lg sm:text-xl text-white/60 max-w-2xl mx-auto mb-10 animate-fade-up animate-delay-200 leading-relaxed">
          The ultimate <strong className="text-purple-300">AI-generated Gen-Z IQ Test</strong>.
          10 questions. 20 seconds each. Discover your brainrot level and flex on the global leaderboard.
        </p>

        {/* CTA Buttons */}
        <div className="flex flex-col sm:flex-row gap-4 justify-center animate-fade-up animate-delay-300">
          <button
            onClick={handleStart}
            className="btn-neon flex items-center gap-2 text-lg px-10 py-5"
          >
            <span>Start Test</span>
            <span className="text-xl">⚡</span>
          </button>
          <button
            onClick={() => { sounds.click(); navigate("/leaderboard"); }}
            className="btn-ghost flex items-center gap-2 text-lg px-8 py-5"
          >
            <span>🏆</span>
            <span>Leaderboard</span>
          </button>
        </div>

        {/* Trust indicators */}
        <div className="flex items-center gap-6 mt-10 animate-fade-up animate-delay-500">
          <div className="flex items-center gap-1.5 text-white/40 text-sm">
            <span>✅</span> Free forever
          </div>
          <div className="w-px h-4 bg-white/10" />
          <div className="flex items-center gap-1.5 text-white/40 text-sm">
            <span>🔒</span> No account
          </div>
          <div className="w-px h-4 bg-white/10" />
          <div className="flex items-center gap-1.5 text-white/40 text-sm">
            <span>⚡</span> Instant results
          </div>
        </div>

        {/* Scroll indicator */}
        <div className="absolute bottom-8 left-1/2 -translate-x-1/2 animate-bounce opacity-40">
          <div className="w-5 h-8 border-2 border-white/30 rounded-full flex justify-center pt-1">
            <div className="w-1 h-2 bg-white/60 rounded-full animate-bounce" />
          </div>
        </div>
      </section>

      {/* ════════════════════════════════════ */}
      {/*            STATS SECTION            */}
      {/* ════════════════════════════════════ */}
      <section className="py-16 px-4">
        <div className="max-w-4xl mx-auto">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {stats.map((stat) => (
              <StatCard key={stat.label} {...stat} />
            ))}
          </div>
        </div>
      </section>

      {/* ════════════════════════════════════ */}
      {/*          BRAINROT LEVELS            */}
      {/* ════════════════════════════════════ */}
      <section className="py-16 px-4">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-10">
            <h2 className="text-3xl sm:text-4xl font-display font-bold text-white mb-3">
              7 Levels of <span className="gradient-text">Brainrot</span>
            </h2>
            <p className="text-white/50">Where will you land?</p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {BRAINROT_LEVELS.map((level, i) => (
              <LevelCard key={level.level} level={level} index={i} />
            ))}
          </div>
        </div>
      </section>

      {/* ════════════════════════════════════ */}
      {/*           FEATURES SECTION          */}
      {/* ════════════════════════════════════ */}
      <section className="py-16 px-4">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-10">
            <h2 className="text-3xl sm:text-4xl font-display font-bold text-white mb-3">
              Why <span className="gradient-text-pink">BrainrotIQ?</span>
            </h2>
            <p className="text-white/50">Not your average quiz app</p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {features.map((f, i) => (
              <FeatureCard key={f.title} {...f} delay={i * 100} />
            ))}
          </div>
        </div>
      </section>

      {/* ════════════════════════════════════ */}
      {/*             FAQ SECTION             */}
      {/* ════════════════════════════════════ */}
      <section className="py-16 px-4">
        <div className="max-w-2xl mx-auto">
          <div className="text-center mb-10">
            <h2 className="text-3xl font-display font-bold text-white mb-3">
              Frequently Asked Questions
            </h2>
          </div>

          <div className="space-y-4">
            {[
              {
                q: "What is the Brainrot IQ Test?",
                a: "It's an AI-powered quiz that tests your Gen-Z slang and internet culture knowledge to determine your 'brainrot level' — a fun scale from NPC to Final Boss Sigma.",
              },
              {
                q: "How does the AI generate questions?",
                a: "We use Groq's lightning-fast API to generate unique, personalized questions in real-time. Every test is different!",
              },
              {
                q: "Is it really free?",
                a: "Yes! 100% free, no account needed, no hidden fees. Just enter your name and play.",
              },
              {
                q: "Can I retake the test?",
                a: "Absolutely! Take it as many times as you want. Each test generates fresh AI questions.",
              },
              {
                q: "How is the score calculated?",
                a: "You get points for each correct answer within the 20-second time limit. Final score is out of 100.",
              },
            ].map((faq, i) => (
              <FAQItem key={i} {...faq} />
            ))}
          </div>
        </div>
      </section>

      {/* ════════════════════════════════════ */}
      {/*             CTA SECTION             */}
      {/* ════════════════════════════════════ */}
      <section className="py-20 px-4">
        <div className="max-w-3xl mx-auto text-center">
          <div className="glass-card p-10 sm:p-16 relative overflow-hidden">
            {/* BG glow */}
            <div className="absolute inset-0 opacity-20"
              style={{ background: "radial-gradient(ellipse at center, #7c3aed, transparent 70%)" }} />

            <div className="relative">
              <div className="text-6xl mb-4 animate-bounce-slow">🧠</div>
              <h2 className="text-3xl sm:text-4xl font-display font-bold text-white mb-4">
                Ready to Find Out?
              </h2>
              <p className="text-white/60 mb-8 text-lg">
                Take the test. Get your level. Flex on your friends.
              </p>
              <button
                onClick={handleStart}
                className="btn-neon text-xl px-12 py-5 mx-auto inline-flex items-center gap-3"
              >
                Start Now ⚡
              </button>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}

function FAQItem({ q, a }) {
  const [open, setOpen] = useState(false);
  return (
    <div
      className="glass-card overflow-hidden cursor-pointer"
      onClick={() => setOpen((p) => !p)}
    >
      <div className="p-4 flex items-center justify-between gap-3">
        <span className="font-semibold text-white/90 text-sm sm:text-base">{q}</span>
        <span className={`text-purple-400 transition-transform duration-300 flex-shrink-0 ${open ? "rotate-180" : ""}`}>
          ▼
        </span>
      </div>
      {open && (
        <div className="px-4 pb-4 animate-fade-in">
          <p className="text-white/60 text-sm leading-relaxed border-t border-white/5 pt-3">
            {a}
          </p>
        </div>
      )}
    </div>
  );
}
